[presets.tokyo-night]
background = "black"
foreground = "white"
accent = "blue"
link = "cyan"
link_missing = "red"
cursor_line = "darkgray"
code = "yellow"
list_selection_foreground = "black"
list_selection_background = "cyan"
heading1 = "cyan"
heading2 = "blue"
heading3 = "magenta"
heading4 = ""
heading5 = ""
heading6 = ""

[presets.gruvbox]
background = "black"
foreground = "white"
accent = "yellow"
link = "magenta"
link_missing = "red"
cursor_line = "darkgray"
code = "yellow"
list_selection_foreground = "black"
list_selection_background = "yellow"
heading1 = "yellow"
heading2 = "magenta"
heading3 = "green"
heading4 = ""
heading5 = ""
heading6 = ""

[presets.dracula]
background = "black"
foreground = "white"
accent = "magenta"
link = "cyan"
link_missing = "red"
cursor_line = "blue"
code = "magenta"
list_selection_foreground = "black"
list_selection_background = "magenta"
heading1 = "magenta"
heading2 = "cyan"
heading3 = "yellow"
heading4 = ""
heading5 = ""
heading6 = ""
